import { FileText, Download, MoreVertical, FileSpreadsheet } from 'lucide-react'
import { ReportFile } from '@/types/report'

interface RecentReportsTableProps {
  reports: ReportFile[]
  onDownload: (report: ReportFile) => void
}

export default function RecentReportsTable({ reports, onDownload }: RecentReportsTableProps) {
  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
      <div className="p-6 border-b border-gray-100 flex justify-between items-center">
        <div>
           <h3 className="text-lg font-bold text-gray-900">Recent Reports</h3>
           <p className="text-sm text-gray-500">Recently generated files available for download</p>
        </div>
      </div>
      
      <div className="overflow-x-auto">
        <table className="w-full text-sm text-left">
          <thead className="bg-gray-50 text-gray-700 font-semibold border-b border-gray-100">
            <tr>
              <th className="px-6 py-4">Report Name</th>
              <th className="px-6 py-4">Type</th>
              <th className="px-6 py-4">Generated By</th>
              <th className="px-6 py-4">Date & Time</th>
              <th className="px-6 py-4">Size</th>
              <th className="px-6 py-4">Status</th>
              <th className="px-6 py-4 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {reports.map((report) => (
              <tr key={report.id} className="hover:bg-gray-50 transition-colors bg-white">
                <td className="px-6 py-4">
                  <div className="flex items-center gap-3">
                    <div className={`p-2 rounded-lg ${
                        report.type === 'PDF' ? 'bg-red-50 text-red-600' : 'bg-green-50 text-green-600'
                    }`}>
                        {report.type === 'PDF' ? <FileText className="w-4 h-4" /> : <FileSpreadsheet className="w-4 h-4" />}
                    </div>
                    <span className="font-medium text-gray-900">{report.name}</span>
                  </div>
                </td>
                <td className="px-6 py-4 text-gray-500">{report.type}</td>
                <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs font-medium">
                            {report.generatedBy.charAt(0)}
                        </div>
                        <span className="text-gray-900">{report.generatedBy}</span>
                    </div>
                </td>
                <td className="px-6 py-4 text-gray-500">{report.date}</td>
                <td className="px-6 py-4 text-gray-500">{report.size}</td>
                <td className="px-6 py-4">
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    report.status === 'Ready' ? 'bg-green-100 text-green-700' : 
                    report.status === 'Processing' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'
                  }`}>
                    {report.status}
                  </span>
                </td>
                <td className="px-6 py-4 text-right">
                  <button 
                    disabled={report.status !== 'Ready'}
                    onClick={() => onDownload(report)}
                    className="inline-flex items-center p-2 text-gray-500 hover:text-primary hover:bg-primary-50 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    title="Download Report"
                  >
                    <Download className="w-4 h-4" />
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
